[workspace]
members = [
    "crates/train",
]
exclude = ["crates/my_bot"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
readme = "README.md"
license = "MIT OR Apache-2.0"

[workspace.dependencies]

