[build]
target = "misc/riscv64-kartoffel-bot.json"

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.riscv64-kartoffel-bot]
rustflags = [
    "-C", "link-arg=-Tmisc/riscv64-kartoffel-bot.ld",
]
